title: Wiki
description: Le Wiki D'Unimakers
theme: bulma-clean-theme
url: https://Unimakers.fr/wiki/

force_theme: light
permalink: pretty
footer_menu: footer_navigation
lang: fr
theme_color: '#2D2D36'
fixed_navbar: top
favicon: favicon.png

paginate: 5
paginate_path: "/blog/page:num"

collections:
  docs:
    output: true
    layout: documentation
    image: https://via.placeholder.com/800x600
    show_sidebar: false
